"use client";

import React, { useEffect, useState } from "react";
import { SectionCreator } from "components/section-header";
import Grid from "@mui/material/Grid";
import Container from "@mui/material/Container";
import LazyImage from "components/LazyImage";
import { H2, H4, H3, H6, Small } from "components/Typography";
import Typography from "@mui/material/Typography";
import Box from "@mui/material/Box";
import { postAPI } from "utils/__api__/ApiServies";
import HtmlRenderer from "components/HtmlRender/HtmlRenderer";

const PrivacyPolicy = () => {
  const [data, setData] = useState([]);
  const getPrivacyPolicy = async () => {
    try {
      const res = await postAPI("get-informations", {
        type: "Privacy Policy",
      });
      if (res.status === 200) {
        setData(res.data.information);
      }
    } catch (error) {
      console.log(error);
    }
  };

  useEffect(() => {
    getPrivacyPolicy();
  }, []);

  if (Object.entries(data).length > 0)
    return (
      <SectionCreator my={2}>
        <Grid
          py={2}
          sx={{ background: "#e8e8e8", width: "100%", textAlign: "center" }}
        >
          <H2 sx={{ textAlign: "center" }}>Privacy Policy</H2>
        </Grid>

        {/* <Grid mt={2}>
          <Box mb={2}>
            <H3>Ecoomerce Terms of Use</H3>
            <Typography pt={1} fontSize={14}>
              We value the trust you place in us and recognize the importance of
              secure transactions and information privacy. This Privacy Policy
              describes how Internet Private Limited and its affiliates
              (collectively “, we, our, us”) collect, use, share or otherwise
              process your personal data through its mobile application, and
              m-site (hereinafter referred to as the “Platform”).
            </Typography>
            <Typography pt={1} fontSize={14}>
              This document is an electronic record in terms of Information
              Technology Act, 2000 and rules there under as applicable and the
              amended provisions pertaining to electronic records in various
              statutes as amended by the Information Technology Act, 2000. This
              electronic record is generated by a computer system and does not
              require any physical or digital signatures.
            </Typography>
            <Typography pt={1} fontSize={14}>
              This document is an electronic record in terms of Information
              Technology Act, 2000 and rules there under as applicable and the
              amended provisions pertaining to electronic records in various
              statutes as amended by the Information Technology Act, 2000. This
              electronic record is generated by a computer system and does not
              require any physical or digital signatures.
            </Typography>
            <Typography pt={1} fontSize={14}>
              This document is an electronic record in terms of Information
              Technology Act, 2000 and rules there under as applicable and the
              amended provisions pertaining to electronic records in various
              statutes as amended by the Information Technology Act, 2000. This
              electronic record is generated by a computer system and does not
              require any physical or digital signatures.
            </Typography>
          </Box>
          <Box>
            <H3>Collection of Your Information</H3>
            <Typography pt={1} fontSize={14}>
              When you use our Platform, we collect and store your information
              which is provided by you from time to time. Once you give us your
              personal data, you are not anonymous to us. Where possible, we
              indicate which fields are required and which fields are optional.
              You always have the option to not provide data by choosing not to
              use a particular service, product or feature on the Platform.
            </Typography>
            <Typography pt={1} fontSize={14}>
              We may track your buying behavior, preferences, and other
              information that you choose to provide on our Platform. We use this
              information to do internal research on our users' demographics,
              interests, and behavior to better understand, protect and serve our
              users. This information is compiled and analyzed on an aggregated
              basis. This information may include the URL that you just came from
              (whether this URL is on our Platform or not), which URL you next go
              to (whether this URL is on our Platform or not), your computer
              browser information, and your IP address.
            </Typography>
            <Typography pt={1} fontSize={14}>
              This document is an electronic record in terms of Information
              Technology Act, 2000 and rules there under as applicable and the
              amended provisions pertaining to electronic records in various
              statutes as amended by the Information Technology Act, 2000. This
              electronic record is generated by a computer system and does not
              require any physical or digital signatures.
            </Typography>
            <Typography pt={1} fontSize={14}>
              This document is an electronic record in terms of Information
              Technology Act, 2000 and rules there under as applicable and the
              amended provisions pertaining to electronic records in various
              statutes as amended by the Information Technology Act, 2000. This
              electronic record is generated by a computer system and does not
              require any physical or digital signatures.
              </Typography>
              </Box>
              </Grid> */}
            <HtmlRenderer html={data?.description || ""} />
      </SectionCreator>
    );

  <></>;
};

export default PrivacyPolicy;
