import { useContext } from "react";
import { ChatContext } from "contexts/ChatContext";

const useChat = () => {
  const {
    checkMessage,
    setCheckMessage,
    handleCheckboxChange,
    moveToChatHandler,
    moveToTrashHandler,
    permanentDeleteHandler,
    showCount,
    setShowCount,
    markAsUnreadHandler,
    markAsReadHandler,
    chats,
    setChats,
    vendorDetails,
    setVendorDetails,
    allChecked,
    setAllChecked,
    etsyCount,
    setEtsyMsgIds,
    sendEtsyIdsHandler,
    etsyMsgIds,
    unreadComposeIds,
    markComposeAsUnread,
    markComposeAsRead,
    pinnedMessageHadler,
    searchText,
    setSearchText,
    searchHandler,
    getSingleVendorDetails,
    page,
    setPage,
    rowsPerPage,
    setRowsPerPage,
    totalCount,
    setTotalCount,
    handleChangePage,
    handleChangeRowsPerPage,
    isLoading,
  } = useContext(ChatContext);

  return {
    checkMessage,
    setCheckMessage,
    handleCheckboxChange,
    moveToChatHandler,
    moveToTrashHandler,
    permanentDeleteHandler,
    showCount,
    setShowCount,
    markAsUnreadHandler,
    markAsReadHandler,
    chats,
    setChats,
    vendorDetails,
    setVendorDetails,
    allChecked,
    setAllChecked,
    etsyCount,
    setEtsyMsgIds,
    sendEtsyIdsHandler,
    etsyMsgIds,
    unreadComposeIds,
    markComposeAsUnread,
    markComposeAsRead,
    pinnedMessageHadler,
    searchText,
    setSearchText,
    searchHandler,
    getSingleVendorDetails,
    page,
    setPage,
    rowsPerPage,
    setRowsPerPage,
    totalCount,
    setTotalCount,
    handleChangePage,
    handleChangeRowsPerPage,
    isLoading,
  };
};

export default useChat;
