"use client";
import React, { useEffect, useState } from "react";
import { SectionCreator } from "components/section-header";
import Grid from "@mui/material/Grid";
import Container from "@mui/material/Container";
import LazyImage from "components/LazyImage";
import { H2, H4, H3, H6, Small } from "components/Typography";
import Typography from "@mui/material/Typography";
import Box from "@mui/material/Box";
import { postAPI } from "utils/__api__/ApiServies";
import parse from "html-react-parser";
import HtmlRenderer from "components/HtmlRender/HtmlRenderer";
// LOCAL CUSTOM COMPONENT

const TermsConditon = () => {
  const [data, setData] = useState({});
  const getTermsAndCondtion = async () => {
    try {
      const res = await postAPI("get-informations", {
        type: "Terms & Conditions",
      });

      if (res.status === 200) {
        setData(res.data.information);
      }
    } catch (error) {
      console.log(error);
    }
  };

  useEffect(() => {
    getTermsAndCondtion();
  }, []);

  if (Object.entries(data).length > 0)
    return (
      <>
        <SectionCreator my={2}>
          <Grid
            py={2}
            sx={{ background: "#e8e8e8", width: "100%", textAlign: "center" }}
          >
            <H2 sx={{ textAlign: "center" }}>Term & Condition</H2>
          </Grid>
{/* 
          <Grid mt={2}>
            <Box mb={2}>
              <H3>Ecoomerce Terms of Use</H3>
              <Typography pt={1} fontSize={14}>
                This document is an electronic record in terms of Information
                Technology Act, 2000 and rules there under as applicable and the
                amended provisions pertaining to electronic records in various
                statutes as amended by the Information Technology Act, 2000. This
                electronic record is generated by a computer system and does not
                require any physical or digital signatures.
              </Typography>
              <Typography pt={1} fontSize={14}>
                This document is an electronic record in terms of Information
                Technology Act, 2000 and rules there under as applicable and the
                amended provisions pertaining to electronic records in various
                statutes as amended by the Information Technology Act, 2000. This
                electronic record is generated by a computer system and does not
                require any physical or digital signatures.
              </Typography>
              <Typography pt={1} fontSize={14}>
                This document is an electronic record in terms of Information
                Technology Act, 2000 and rules there under as applicable and the
                amended provisions pertaining to electronic records in various
                statutes as amended by the Information Technology Act, 2000. This
                electronic record is generated by a computer system and does not
                require any physical or digital signatures.
              </Typography>
              <Typography pt={1} fontSize={14}>
                This document is an electronic record in terms of Information
                Technology Act, 2000 and rules there under as applicable and the
                amended provisions pertaining to electronic records in various
                statutes as amended by the Information Technology Act, 2000. This
                electronic record is generated by a computer system and does not
                require any physical or digital signatures.
              </Typography>
            </Box>
            <Box>
              <H3>Ecoomerce Terms of Use</H3>
              <Typography pt={1} fontSize={14}>
                This document is an electronic record in terms of Information
                Technology Act, 2000 and rules there under as applicable and the
                amended provisions pertaining to electronic records in various
                statutes as amended by the Information Technology Act, 2000. This
                electronic record is generated by a computer system and does not
                require any physical or digital signatures.
              </Typography>
              <Typography pt={1} fontSize={14}>
                This document is an electronic record in terms of Information
                Technology Act, 2000 and rules there under as applicable and the
                amended provisions pertaining to electronic records in various
                statutes as amended by the Information Technology Act, 2000. This
                electronic record is generated by a computer system and does not
                require any physical or digital signatures.
              </Typography>
              <Typography pt={1} fontSize={14}>
                This document is an electronic record in terms of Information
                Technology Act, 2000 and rules there under as applicable and the
                amended provisions pertaining to electronic records in various
                statutes as amended by the Information Technology Act, 2000. This
                electronic record is generated by a computer system and does not
                require any physical or digital signatures.
              </Typography>
              <Typography pt={1} fontSize={14}>
                This document is an electronic record in terms of Information
                Technology Act, 2000 and rules there under as applicable and the
                amended provisions pertaining to electronic records in various
                statutes as amended by the Information Technology Act, 2000. This
                electronic record is generated by a computer system and does not
                require any physical or digital signatures.
              </Typography>
            </Box>
          </Grid> */}
          <HtmlRenderer html={ data?.description || ""} />
        </SectionCreator>
      </>

    );
  <></>;
};

export default TermsConditon;
